on:
  push:
    branches:
      - add-multiple-changelogPath
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      # - uses: google-github-actions/release-please-action@v3
      #   with:
      #     release-type: node
      #     package-name: testing-repo
      #     command: manifest
    - name: Copy the Readmes
      run: |
        find . -type f -name "CHANGELOG.md" | while read fname; do
          dirname=`dirname "$fname"`
          foldername=`basename "$dirname"`
          filename=`basename "$fname"`
          newname=`echo "$dirname" | sed -e "s/ /_/g"`
          cp "${dirname}/$filename" "./docs/_myfolder/${foldername}.md"
        done
    - name: Commit files
      run: |
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: add-multiple-changelogPath